const resList = [
  {
    id: "74453",
    name: "Domino's Pizza",
    cloudinaryImageId: "bz9zkh2aqywjhpankb07",
    cuisines: ["Pizzas"],
    avgRating: "4.0",
    costForTwo: 40000,
    deliveryTime: 45,
  },
  {
    id: "410476",
    name: "The Brooklyn Creamery - Healthy Ice Cream",
    cloudinaryImageId: "ldtibwymvzehvmdwl8la",
    cuisines: ["Desserts", "Ice Cream", "Healthy Food"],
    avgRating: "4.4",
    costForTwo: 20000,
    deliveryTime: 31,
  },
  {
    id: "81094",
    name: "Richie Rich Juices & Shakes",
    cloudinaryImageId: "nyp7yrzwc1dc2xqfkydk",
    cuisines: ["Ice Cream"],
    avgRating: "3.9",
    costForTwo: 25000,
    deliveryTime: 30,
  },
  {
    id: "311443",
    name: "Siddhi Icecream & Thick Shake",
    cloudinaryImageId: "spd3y5gok3vvwqulgmda",
    cuisines: ["Ice Cream", "Juices", "Desserts", "Beverages"],
    avgRating: "4.5",
    costForTwo: 20000,
    deliveryTime: 30,
  },
  {
    id: "307070",
    name: "Pizza Pie",
    cloudinaryImageId: "bvr70adr30ejyr5ua79k",
    cuisines: ["Pizzas"],
    avgRating: "4.2",
    costForTwo: 30000,
    deliveryTime: 37,
  },
  {
    id: "76858",
    name: "Feeling Hungry",
    cloudinaryImageId: "oxsb5mr1xsmhnxhunjsc",
    cuisines: ["Chinese", "North Indian", "Biryani"],
    avgRating: "3.2",
    costForTwo: 2000,
    deliveryTime: 35,
  },
  {
    id: "617279",
    name: "Malaxmi Fast Food",
    cloudinaryImageId: "agkm7cflq72tkualhstb",
    cuisines: ["Fast Food", "Pizzas", "Snacks", "Beverages"],
    avgRating: "4.0",
    costForTwo: 20000,
    deliveryTime: 44,
  },
  {
    id: "469264",
    name: "Dessert House",
    cloudinaryImageId: "jegpumsjcmomksbr2sxr",
    cuisines: ["Desserts", "Ice Cream"],
    avgRating: "4.5",
    costForTwo: 15000,
    deliveryTime: 27,
  },
  {
    id: "395204",
    name: "McDonald's Gourmet Burger Collection",
    cloudinaryImageId: "wzbo5xivr8hstl0vxzcm",
    cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
    avgRating: "4.2",
    costForTwo: 50000,
    deliveryTime: 31,
  },
  {
    id: "193541",
    name: "Behrouz Biryani",
    cloudinaryImageId: "craozjakzx7sll2uracb",
    cuisines: [
      "Biryani",
      "Mughlai",
      "Lucknowi",
      "Hyderabadi",
      "Kebabs",
      "North Indian",
      "Persian",
      "Desserts",
    ],
    avgRating: "4.3",
    costForTwo: 50000,
    deliveryTime: 49,
  },
  {
    id: "475510",
    name: "Momos House",
    cloudinaryImageId: "vmold2zualdrrypxcvue",
    cuisines: ["Fast Food"],
    avgRating: "4.1",
    costForTwo: 20000,
    deliveryTime: 31,
  },
  {
    id: "127596",
    name: "Sabir Chicken",
    cloudinaryImageId: "kilrdjqt8chduasii5ni",
    cuisines: ["North Indian", "Biryani"],
    avgRating: "4.1",
    costForTwo: 30000,
    deliveryTime: 30,
  },
  {
    id: "64656",
    name: "Mahesh Pav Bhaji",
    cloudinaryImageId: "84d3bea985f13bd980dc39c9c73bc87f",
    cuisines: ["Desserts", "Chinese", "South Indian", "Ice Cream", "Pizzas"],
    avgRating: "4.1",
    costForTwo: 25000,
    deliveryTime: 36,
  },
  {
    id: "255204",
    name: "The Dango Cake Shop",
    cloudinaryImageId: "mnvfpsoealkflze4e5qi",
    cuisines: ["Bakery"],
    avgRating: "4.2",
    costForTwo: 27000,
    deliveryTime: 34,
  },
  {
    id: "664656",
    name: "Cheezylicious Cafe",
    cloudinaryImageId: "fda9ad56b9d62070fec105cd93693129",
    cuisines: ["Cafe", "Fast Food", "Chinese", "Snacks", "Italian", "Mexican"],
    avgRating: "3.9",
    costForTwo: 15000,
    deliveryTime: 38,
  },
];

export default resList;
